### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by ghost** [erikberglund/SwiftPrivilegedHelper#7]
Hi 
i found new bug and won't able to compile code , 

```
Showing Recent Messages
: /Users/deepak/Library/Developer/Xcode/DerivedData/SwiftPrivilegedHelperApplication-bokpebolhowlobfwharkznpkrgko/Build/Intermediates.noindex/SwiftPrivilegedHelperApplication.build/Debug/com.github.erikberglund.SwiftPrivilegedHelper.build/Script-5361D213216254BC0036E296.sh: line 2: /Users/deepak/Downloads/SwiftPrivilegedHelper-master: is a directory
```

see below screenshot for more details 

![screen shot 2018-10-05 at 6 09 25 pm](https://user-images.githubusercontent.com/9814566/46535765-00f7f800-c8ca-11e8-82aa-9cd7bb31c817.png)

**Comment by ghost** [comment]
Hi i found fix too , 
in download i already have old project so your script fails in this , just deleted old and now all good 

continuing testing will post result soon

**Comment by jamalwill325** [comment]
I'm having the same problem

**Comment by ghost** [comment]
copy it to desktop and try
