### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jariz** [erikberglund/SwiftPrivilegedHelper#9]
Hiya, I'm gonna reuse parts of your application in a (free, oss) app of mine, so it's kind of important for me to know the license, as it'll likely influence my own choice of license, and on top of that, in it's current state I can't even use it - legally speaking.   
If you may not know, even though a piece of software is 'open source', it does not make it - legally - reusable perse.  
I'd suggest the MIT license, but check out https://choosealicense.com/ if you want to know what other options are available.

**Comment by erikberglund** [comment]
Hey, thanks for this. I'm not good at remembering to put licensens up. This can be used as freely as possible, so I guess MIT should be the best option then.

**Comment by erikberglund** [comment]
Added the MIT License now.
